Draft: Offramp
RampNetwork/ramp-sdk-ios pull request #7
Opened 2022-05-19 10:57 UTC by mateuszjablonski

2022-06-17 09:04 UTC, jakubsta requested changes

2022-06-17 09:04 UTC, jakubsta commented on Sources/Ramp/Configuration.swift
> +        urlComponents.appendQueryItem(name: "enabledFlow", value: enabledFlow?.map(\.rawValue).joined(separator: ","))
```suggestion
        urlComponents.appendQueryItem(name: "enabledFlows", value: enabledFlows?.map(\.rawValue).joined(separator: ","))
```

2022-06-17 09:04 UTC, jakubsta commented on Sources/Ramp/Configuration.swift
> +    public var enabledFlow: [Flow]? = nil
```suggestion
    public var enabledFlows: [Flow]? = nil
```

2022-06-17 09:10 UTC, jakubsta commented on Sources/Ramp/Configuration.swift
> +        urlComponents.appendQueryItem(name: "enabledFlow", value: enabledFlow?.map(\.rawValue).joined(separator: ","))
please transform it to uppercase.

2022-08-18 11:14 UTC, mateuszjablonski commented on Ramp.podspec
> +    spec.source = { :git => 'https://github.com/RampNetwork/ramp-sdk-ios.git', :branch => 'offramp' }
don't forget to change it back when releasing

2022-11-15 13:04 UTC, jakubsta commented on Sources/Ramp/Configuration.swift
> +    public var swapAsset: String?
```suggestion
    public var swapAsset: String?
    public var offrampAsset: String?
```

2022-11-15 13:05 UTC, jakubsta commented on Sources/Ramp/Configuration.swift
> +        urlComponents.appendQueryItem(name: "swapAsset", value: swapAsset)
```suggestion
        urlComponents.appendQueryItem(name: "swapAsset", value: swapAsset)
        urlComponents.appendQueryItem(name: "offrampAsset", value: offrampAsset)      
```

2022-11-15 13:15 UTC, merged